 export const CHANGE_ROUTE ="CHANGE_ROUTE";
 export const CHANGE_SIGNUP_LOGIN = "CHANGE_SIGNUP_LOGIN";
 export const CHANGE_LOGGEDIN ="CHANGE_LOGGEDIN";
 export const CHANGE_OPTION = "CHANGE_OPTION";
export const CHANGE_USER = "CHANGE_USER";
export const SELECT_ARTICLE = "SELECT_ARTICLE";
export const MODIFY_PROFILE = "MODIFY_PROFILE";
export const SEND_PROFILE = "SEND_PROFILE"